# Unit Root Test

A presence of unit root necessitates special treatment in empirical
applications. Therefore it is of vital importance to pre-test the
existence of unit root.

However, there is no clear cut between stationary and unit root
processes for finite samples. Consider an AR(1) process with
$\phi=0.999$, which is a stationary process that behaves very close to a
unit root process. In other words, unit root and stationary processes
differ in their implications at *infinite* time horizons, but for any
*finite* number of observations, there is always a representation from
either class of models that could account for all the observed features
of the data. So it is *not* possible to tell whether the DGP is
stationary or not. We can formulate testable hypothesis only if we were
willing to restrict the class of models being considered. Suppose we
were committed to an AR(1) model: $y_t =\phi y_{t-1}+\epsilon_t$. The
hypothesis $\phi=1$ is definitely testable.

## Dickey-Fuller Test

Consider an AR(1) process

$$
y_t = \phi y_{t-1} + u_t,
$$

assuming no series correlation in the innovations
$u_t\sim IID(0,\sigma^2)$. We have shown that under the hypothesis
$\phi=1$,

$$
T(\hat\phi-1)\to\frac{\int W dW}{\int W^2 dt}.
$$

We can the hypothesis $H_0:\ \phi=1$ utilizing this distribution. The
critical values can be obtained by Monte Carlo simulations. The test was
proposed by Fuller (1976).

The Dickey-Fuller tests involve three sets of equations depending
whether a drift or trend is included, assuming $iid$ innovations.

$$
\begin{aligned}
\Delta y_t &= \gamma y_{t-1} + u_t \\
\Delta y_t &= \alpha_0 + \gamma y_{t-1} + u_t\\
\Delta y_t &= \alpha_0 + \gamma y_{t-1} + \alpha_2t + u_t
\end{aligned}
$$

Testing $\phi=1$ is equivalent to testing $\gamma=0$. The critical
values depends on the form of the regression and the sample size
(including a drift or trend results in different limiting distributions
for $\gamma$).

| Model                | Hypothesis                   | 95%   | 99%   |
|----------------------|------------------------------|-------|-------|
| Default              | $\gamma=0$                   | -1.95 | -2.60 |
| With drift           | $\gamma=0$                   | -2.89 | -3.51 |
|                      | $\alpha_0=\gamma=0$          | 4.71  | 6.70  |
| With drift and trend | $\gamma=0$                   | -3.45 | -4.04 |
|                      | $\gamma=\alpha_2=0$          | 6.49  | 8.73  |
|                      | $\alpha_0=\gamma=\alpha_2=0$ | 4.88  | 6.50  |

: Critical values of Dickey-Fuller tests

## Augmented Dickey-Fuller Test

The assumption that $\epsilon_t$ being uncorrelated is too strong for
empirical applications. Suppose the data is generated by an AR($p$)
process with an unit root,

$$
\begin{aligned}
a(L) y_t &= \epsilon_t \\
(1-L)y_t &= \underbrace{b^{-1}(L)\epsilon_t}_{u_t}
\end{aligned}
$$

where $a(L) = (1-L)b(L)$ in which $b(L)$ is stationary. In this case,
$u_t$ will be autocorrelated. In empirical works, it is more reasonable
to assume $u_t$ being serially correlated.

If we difference $y_t$ once, we have

$$
\begin{aligned}
b(L)\Delta y_t &= \epsilon_t \\
y_t &= y_{t-1} + \sum_{j=1}^{p}\beta_j\Delta y_{t-j} + \epsilon_t
\end{aligned}
$$This motivates Dickey-Fuller tests with lags $\{\Delta y_{t-j}\}$.
This is called augmented Dickey-Fuller test. The set of equations change
to

$$
\begin{aligned}
\Delta y_t &= \gamma y_{t-1} + \sum_{j=1}^{p}\beta_j\Delta y_{t-j} + u_t \\
\Delta y_t &= \alpha_0 + \gamma y_{t-1} + \sum_{j=1}^{p}\beta_j\Delta y_{t-j} + u_t\\
\Delta y_t &= \alpha_0 + \gamma y_{t-1} + \alpha_2t + \sum_{j=1}^{p}\beta_j\Delta y_{t-j} + u_t
\end{aligned}
$$

The coefficients on $\Delta y_{t-j}$ converge to Gaussian. The
coefficient on $y_{t-1}$ converges to non-standard distribution. The
critical values are unchanged with lags are included.

## Phillips-Perron Test

Another approach to test unit root is proposed by Phillips and Perron
(1988), which also assumes autocorrelated errors. Our Brownian motion
theories derived from $iid$ innovations can be extended to
autocorrelated innovations:

$$
\xi_T(r) = \frac{1}{\sqrt T}\sum_{t=1}^{Tr} u_t \to \omega W(r)
$$

where $\omega^2 = \sum_{-\infty}^{\infty}\gamma_j$ is the long-run
variance for the autocorrelated process $\{u_t\}$.

But, with autocorrelated errors, the limiting distribution of $\hat\phi$
is slightly different, since

$$
\begin{aligned}
\frac{1}{T}\sum_t y_{t-1}u_t &= \frac{1}{2T}y_T^2 - \frac{1}{2T}\sum_t u_t^2 \\
&\to \frac{1}{2}[\omega^2W^2(1) - \sigma_u^2] \\
&\to \omega^2\int W dW + \frac{\omega^2 - \sigma_u^2}{2}
\end{aligned}
$$

where $\frac{\omega^2-\sigma_u^2}{2}$ is a "nuisance" parameter. The
Phillips and Perron proposed a test statistics correcting the nuisance
parameter:

$$
T(\hat\phi -1 ) + \frac{\frac{1}{2}\hat\omega^2 - \hat\sigma_u^2}{\frac{1}{T^2}\sum y_t^2} \to \frac{\int W dW}{\int W^2 dt}
$$

where $\hat\omega^2$ can be estimated by Newey-West, $\hat\sigma_u^2$ is
the estimated variance of the residuals. After the correction, the unit
root test can be applied to processes with autocorrelated errors.
