project:
  type: book

book:
  title: "Time Series Analysis for Economists"
  author: "Zem Wang"
  date: "January 2024"
  chapters:
    - index.qmd
    - part: "The Basics"
      chapters: 
        - 01_base.qmd
        - 02_dec.qmd
        - 03_acf.qmd
        - 04_st.qmd
    - part: "ARIMA Model"
      chapters: 
        - 05_spec.qmd
        - 06_ar.qmd
        - 07_ma.qmd
        - 08_arma.qmd
        - 09_wold.qmd
    - part: "Time Series Regression"
      chapters: 
        - 10_ols.qmd
        - 11_ols2.qmd
        - 12_mle.qmd
        - 13_fc.qmd
        - 14_dce.qmd
        - 15_ssf.qmd
        - 16_adl.qmd
        - 17_iv.qmd
    - part: "Nonstationary Time Series"
      chapters: 
        - 18_sp.qmd
        - 19_ts.qmd
        - 20_uni.qmd
        - 21_ito.qmd
        - 22_uni2.qmd
    - sum.qmd
    - ref.qmd

bibliography: ref.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    pdf-engine: pdflatex



