project:
  type: book

book:
  title: "Time Series Analysis for Economists"
  author: "Z.WANG"
  date: "23 Feb 2024"
  chapters:
    - index.qmd
    - part: "The Basics"
      chapters: 
        - 01_base.qmd
        - 02_dec.qmd
        - 03_acf.qmd
        - 04_st.qmd
    - part: "ARIMA Model"
      chapters: 
        - 05_spec.qmd
        - 06_ar.qmd
        - 07_ma.qmd
        - 08_arma.qmd
        - 09_wold.qmd
    - part: "Time Series Regression"
      chapters: 
        - 10_ols.qmd
        - 11_ols2.qmd
        - 12_mle.qmd
        - 13_fc.qmd
        - 14_dce.qmd
        - 15_ssf.qmd
        - 16_adl.qmd
        - 17_iv.qmd
    - part: "Nonstationary Time Series"
      chapters: 
        - 18_sp.qmd
        - 19_ts.qmd
        - 20_uni.qmd
        - 21_ito.qmd
        - 22_uni2.qmd
        - 23_ut.qmd
        - 24_co.qmd
    - part: "Vector Autoregression"
      chapters: 
        - 25_sys.qmd
        - 26_var.qmd
        - 27_var2.qmd
        - 28_gc.qmd
        - 29_svar.qmd
        - 30_irf.qmd
        - 31_dfm.qmd
        - 32_uvar.qmd
        - 33_vecm.qmd
    - part: "Bayesian Analysis"
      chapters: 
        - 34_bayes.qmd
        - 35_blm.qmd
        - 36_bvar.qmd
    - sum.qmd
    - ref.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    pdf-engine: pdflatex



