project:
  type: book

book:
  title: "Applied Time Series Analysis"
  author: "Zem Wang"
  date: "January 2024"
  chapters:
    - index.qmd
    - part: "The Basics"
      chapters: 
        - basics.qmd
        - decomp.qmd
        - autocov.qmd
        - stationary.qmd
    - part: "ARIMA Model"
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



