# Preface {.unnumbered}

Empirical macroeconomics often involves dealing with time series data, such as GDP, inflation, and interest rates, which differ from the techniques employed in cross-sectional studies. This book aims to bridge the gap between introductory time series textbooks and theoretical econometrics. In empirical research, a basic understanding of the topic is often insufficient. As it could be potentially dangerous to apply advanced techniques without understanding the underlying theories, the limitations and drawbacks of the techniques. On the other hand, for practical purposes, an in-depth study of advanced econometric theories would be excessive. For example, introductory textbooks would emphasize the risk of applying OLS to non-stationary time series, as it might lead to spurious regression. Students usually accept this as a rule of thumb without fully understanding the reasons behind it. However, a thorough study of Itô calculus and stochastic processes is not necessary for practitioners.

The goal of this book is to introduce the various time series topics that are important for understanding and conducting empirical research. It is written with macroeconomic applications in mind, although the techniques discussed can also be applied to other disciplines. In addition to introducing basic concepts and applications (running a regression and interpreting the results), the book strives to offer a higher level of understanding regarding why certain methods work and others do not. However, it does not seek to provide a rigorous treatment with fully formal proofs; instead, it focuses on providing intuitive explanations. As a result, readers will occasionally encounter non-rigorous proofs when a more formal treatment is deemed unnecessary for a understanding required in applied works. This book can be seen as an intermediate reading between undergraduate econometrics and more rigorous treatments of the subject, such as Hamilton's *Time Series Analysis*.

The materials presented are drawn from or influenced by various sources. I list all of them in the References at the end of the book without citing them individually in the context.

Regarding notations, I use lowercase letters for random variables, such as $x_t$ and $y_t$. Realizations of random variables are expressed as $x_1$, $x_2$, and so on. The context will make it clear whether I am referring to a random variable or its realizations. Capital letters are reserved for matrices, such as $\mathbf{A}$ and $\mathbf{B}$. Vectors are denoted in bold, such as $\mathbf{x}_t$ and $\mathbf{y}_t$, although sometimes I do not explicitly distinguish between vectors and scalars. Greek letters are preferred for parameters, such as $\alpha$ and $\beta$. Estimators are indicated with a hat, such as $\hat{\alpha}$ and $\hat{\beta}$.

I use the statistical language R whenever programming is involved. I am aware that there are many time series solutions available in R. To avoid burdening readers with excessive packages, I stick to base R as much as possible with a little help from the *zoo* package.

I would like to emphasize that my knowledge and understanding of the subject are limited, and I acknowledge that there may be mistakes or areas where I could have provided a more accurate explanation. I deeply appreciate any feedback or corrections from readers that could improve the accuracy and clarity of this book. Your input is invaluable, and I am grateful for your assistance in making this book as informative and reliable as possible.
